# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('checked_out', models.BooleanField(default=False, help_text='is checked out')),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Prepared', 'Prepared'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=200)),
                ('payment_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Prepared', 'Prepared'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('ordered_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Is getting sold?')),
                ('cost', models.FloatField(help_text='Cost of the item')),
                ('capacity', models.IntegerField(help_text='Total items present in the shop')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User'),
        ),
    ]
