# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Prepared', 'Prepared'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Order Received', max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid by Cash', 'Paid by Cash'), ('Paid by Paytm', 'Paid by Paytm')], default='Not Paid', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='capacity',
            field=models.IntegerField(help_text='Total items present in the shop', null=True),
        ),
    ]
