# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180302_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_name',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='item_name_idly', max_length=200),
            preserve_default=False,
        ),
    ]
