# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180302_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('checked_out', models.BooleanField(default=False, help_text='is checked out')),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Prepared', 'Prepared'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Order Received', max_length=200)),
                ('payment_status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid by Cash', 'Paid by Cash'), ('Paid by Paytm', 'Paid by Paytm')], default='Not Paid', max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
